[variables]
PORT = "3333"
HOSTNAME = "0.0.0.0"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm run build",
  "cp -r public .next/standalone/public",
  "cp -r .next/static .next/standalone/.next/static"
]

[start]
cmd = "node .next/standalone/server.js"
